# Generated by Django 4.2.4 on 2023-11-07 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must start with a '+359' followed by 9 digits", regex='^\\+359\\d{9}$')]),
        ),
    ]
