# Generated by Django 4.2.4 on 2023-10-20 14:47

from django.db import migrations
import random


def add_barcode(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    all_products = Product.objects.all()

    barcodes = random.sample(
        range(100000000, 999999999),
        len(all_products)
    )

    for i in range(len(all_products)):
        current_product = all_products[i]
        current_product.barcode = barcodes[i]
        current_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_created_on_product_last_edited_on'),
    ]

    operations = [
    ]
