# Generated by Django 4.2.4 on 2023-11-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
