# Generated by Django 4.2.4 on 2023-11-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_last_update_actor_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='all_actor_movies', to='main_app.actor'),
        ),
    ]
